tags_where_general = ["indoor","outdoor"]

tags_where_indoor_detail = [
    "at home",
    "in the classroom",
    "in a restaurant",
    "in a shopping mall",
    "in a hospital",
    "in a museum",
    "in a library",
    "at a kids' play area"
]

tags_where_outdoor_detail = [
    "in a park",
    "in a garden",
    "in a sandpit",
    "in the playground",
    "on the beach",
    "in the forest"
]

tags_what = [
    "the baby is lifting head up",
    "the baby is crawling",
    "the baby is playing with toys",
    "the baby is eating baby food",
    "the baby is drinking milk",
    "the baby is smiling",
    "the baby is crying",
    "the baby is receiving a vaccine",
    "the baby is yawning",
    "the baby is taking a bath",
    "lying idly",
    "standing idly"
    "posing for a picture",
    "running",
    "dancing",
    "swimming",
    "sleeping",
    "playing arcade games",
    "playing with sand",
    "playing badminton",
    "playing basketball",
    "playing football",
    "playing roller skating",
    "playing on a slide",
    "playing on a swing",
    "playing on a seesaw",
    "playing with dolls",
    "playing with a dog",
    "playing with a kite",
    "playing with ocean balls",
    "playing with fireworks",
    "playing with Lego blocks",
    "playing chess",
    "playing with toys",
    "playing with balloons",
    "playing in the snow",
    "drink water",
    "eating food",
    "eating fruit",
    "eating ice cream",
    "eating cotton candy",
    "feeding the fish",
    "feeding the pigeons",
    "feeding a rabbit",
    "feeding a sheep",
    "feeding a cow",
    "feeding a guinea pig",
    "riding a bike",
    "riding a carousel",
    "drawing a picture",
    "reading a book",
    "making a funny face",
    "watching cartoons",
]