tags_where_general = ["indoor","outdoor"]

tags_where_indoor_detail = [
    "at home",
    "in the classroom",
    "in a car",
    "in a restaurant",
    "in a shopping mall",
    "in a hospital",
    "in a museum",
    "in a library",
    "in a zoo",
    "at a kids' play area"
]

tags_where_outdoor_detail = [
    "in a park",
    "in a garden",
    "in a sandpit",
    "in the playground",
    "on the beach",
    "in the forest"
]

tags_people_count = [
    "no people",
    "one people",
    "two people",
    "three people",
    "many people"
]

tags_what = [
    "a group photo of many children",
    "a family photo with everyone",
    "a woman holding a baby",
    "an infant lying",
    "taking a bath",
    "lying idly",
    "standing idly",
    "posing for a picture",
    "running",
    "dancing",
    "swimming",
    "family camping",
    "getting a haircut",
    "celebrating birthday",
    "celebrating Halloween",
    "displaying their painting",
    "sitting on the couch",
    "sleeping in bed",
    "sleeping on the couch",
    "sleeping in the infant crib",
    "sleeping in the child safety seat",
    "sitting on the ground",
    "sitting on the grass",
    "sitting in the water",
    "playing arcade games",
    "playing with sand",
    "playing badminton",
    "playing basketball",
    "playing football",
    "playing roller skating",
    "playing on a slide",
    "playing on a swing",
    "playing on a seesaw",
    "playing on a scooter",
    "playing with dolls",
    "playing with a dog",
    "playing with a cat",
    "playing with a kite",
    "playing with ocean balls",
    "playing with fireworks",
    "playing with Lego blocks",
    "playing with playdough",
    "playing chess",
    "playing with toys",
    "playing with balloons",
    "playing in the snow",
    "playing a musical instrument",
    "playing bowling",
    "playing with water guns",
    "drink water",
    "eating food",
    "eating fruit",
    "eating ice cream",
    "eating cotton candy",
    "feeding the fish",
    "feeding the pigeons",
    "feeding a rabbit",
    "feeding a sheep",
    "feeding a cow",
    "feeding a pig",
    "riding a bike",
    "riding a carousel",
    "riding in a baby carriage",
    "drawing a picture",
    "reading a book",
    "making a funny face",
    "watching cartoons",
    "catch fish in the stream",
]